version: "0.2"
ignorePaths: []
dictionaryDefinitions:
  - name: ui-for-etw
    path: ./.vscode/cspell-ui-for-etw.txt
    addWords: true
dictionaries:
  - ui-for-etw
words: []
ignoreWords: []
import: []
