# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: UIforETW/UIforETW.sln

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest"]
        config: ["Debug", "Release"]
        platform: ["ARM64", "Win32", "x64"]
        solution: ["UIforETW/UIforETW.sln"]

    runs-on: windows-latest

    # Build ⚙️ Debug
    name: "Build | ${{ matrix.config }} ⚙️"

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup MSBuild 🛠️
        uses: microsoft/setup-msbuild@v2

      - name: NuGet Restore 📩
        working-directory: ${{ github.workspace }}
        run: nuget restore "${{ matrix.solution }}"

      - name: Build ⚙️
        working-directory: ${{ github.workspace }}
        run: msbuild /m /p:Platform="${{ matrix.platform }}" /p:Configuration="${{ matrix.config }}" "${{ matrix.solution }}"
